/**
 * Shared constants used across the app.
 *
 * Keep this file tiny and dependency-free. For table-row types and enum
 * unions, import from `@/lib/supabase/database.types` (auto-generated by
 * `./ops.sh gen-types`) — that is the single source of truth for DB shape.
 */

/** Cascadia Forestry Inc — fixed company UUID. */
export const CASCADIA_ID = '00000000-0000-0000-0000-000000000001'

/** Ramos Reforestation Inc — fixed company UUID. */
export const RAMOS_ID = '00000000-0000-0000-0000-000000000002'
