// Mock data for the Cascadia / Ramos Operations Platform

export type Role = 'admin' | 'owner' | 'foreman' | 'office' | 'employee' | 'client'
export type Company = 'all' | 'cascadia' | 'ramos'
export type Language = 'en' | 'es'

export interface Contract {
  id: string
  name: string
  contractNumber: string
  company: 'cascadia' | 'ramos'
  landowner: string
  workType: string
  location: string
  county: string
  state: string
  crewCount: number
  progress: number
  totalUnits: number
  completedUnits: number
  status: 'active' | 'upcoming' | 'seasonal' | 'completed'
  startDate: string
  contractValue: number
  bond: number
  bondPaid: boolean
  estimatedCompletion: string
  daysLeft: number
  budgetBurn: number
  foremanId: string
}

export interface Employee {
  id: string
  name: string
  initials: string
  role: 'foreman' | 'driver' | 'crew'
  company: 'cascadia' | 'ramos'
  rate: number
  rateType: 'hourly' | 'daily'
  hoursThisWeek: number
  otHours: number
  driveHours: number
  h2b: boolean
  active: boolean
  compliance: { item: string; expiration: string; daysLeft: number; status: 'current' | 'expiring' | 'expired' }[]
}

export interface TimeSheet {
  id: string
  date: string
  foremanName: string
  contractName: string
  unit: string
  crewCount: number
  hours: number
  production: number
  productionUnit: string
  otHours: number
  status: 'pending' | 'approved' | 'rejected'
}

export interface Alert {
  id: string
  type: 'critical' | 'warning' | 'info' | 'success'
  title: string
  detail: string
  countdown?: string
  module: string
}

// KPI sparkline data (7 days)
export const sparklineData = {
  crew: [22, 24, 26, 28, 25, 27, 28],
  production: [24500, 26200, 27800, 25100, 28300, 27050, 29100],
  payroll: [5200, 5400, 5800, 6100, 5900, 6000, 5940],
  pendingSheets: [3, 2, 2, 1, 3, 2, 1],
  otRisk: [1, 2, 2, 3, 2, 3, 3],
}

export const contracts: Contract[] = [
  {
    id: 'vanessa',
    name: 'Vanessa',
    contractNumber: 'CASCADWTHI202',
    company: 'cascadia',
    landowner: 'Weyerhaeuser',
    workType: 'Planting',
    location: 'Cowlitz CO, WA',
    county: 'Cowlitz',
    state: 'WA',
    crewCount: 12,
    progress: 67,
    totalUnits: 18,
    completedUnits: 12,
    status: 'active',
    startDate: 'Oct 15, 2025',
    contractValue: 187000,
    bond: 18700,
    bondPaid: true,
    estimatedCompletion: 'Mar 14',
    daysLeft: 21,
    budgetBurn: 52,
    foremanId: 'agustin',
  },
  {
    id: 'kirk',
    name: 'Kirk',
    contractNumber: 'CASCADWTHI203',
    company: 'cascadia',
    landowner: 'Weyerhaeuser',
    workType: 'Planting',
    location: 'Columbia CO, OR',
    county: 'Columbia',
    state: 'OR',
    crewCount: 14,
    progress: 36,
    totalUnits: 22,
    completedUnits: 8,
    status: 'active',
    startDate: 'Nov 1, 2025',
    contractValue: 215000,
    bond: 21500,
    bondPaid: true,
    estimatedCompletion: 'Apr 10',
    daysLeft: 48,
    budgetBurn: 38,
    foremanId: 'maya',
  },
  {
    id: 'dnr-lewis',
    name: 'DNR Lewis',
    contractNumber: 'DNRLEW2026',
    company: 'cascadia',
    landowner: 'WA DNR',
    workType: 'Thinning',
    location: 'Lewis CO, WA',
    county: 'Lewis',
    state: 'WA',
    crewCount: 0,
    progress: 0,
    totalUnits: 8,
    completedUnits: 0,
    status: 'upcoming',
    startDate: 'Mar 15, 2026',
    contractValue: 95000,
    bond: 9500,
    bondPaid: false,
    estimatedCompletion: 'Jun 30',
    daysLeft: 130,
    budgetBurn: 0,
    foremanId: '',
  },
  {
    id: 'papa-bear',
    name: 'Papa Bear',
    contractNumber: 'VAAGPB2025',
    company: 'cascadia',
    landowner: 'Vaagen Bros',
    workType: 'Thinning',
    location: 'Okanogan CO, WA',
    county: 'Okanogan',
    state: 'WA',
    crewCount: 0,
    progress: 0,
    totalUnits: 6,
    completedUnits: 0,
    status: 'seasonal',
    startDate: 'Jun 1, 2026',
    contractValue: 120000,
    bond: 12000,
    bondPaid: false,
    estimatedCompletion: 'Sep 30',
    daysLeft: 220,
    budgetBurn: 0,
    foremanId: '',
  },
  {
    id: 'vaagen-krumm',
    name: 'Vaagen Krumm',
    contractNumber: 'VAAGKR2025',
    company: 'cascadia',
    landowner: 'Vaagen Bros',
    workType: 'Hand Piling',
    location: 'Okanogan CO, WA',
    county: 'Okanogan',
    state: 'WA',
    crewCount: 0,
    progress: 0,
    totalUnits: 4,
    completedUnits: 0,
    status: 'seasonal',
    startDate: 'Jul 1, 2026',
    contractValue: 80000,
    bond: 8000,
    bondPaid: false,
    estimatedCompletion: 'Oct 15',
    daysLeft: 235,
    budgetBurn: 0,
    foremanId: '',
  },
  {
    id: 'chilton',
    name: 'Chilton',
    contractNumber: 'CASCADCH2025',
    company: 'cascadia',
    landowner: 'Weyerhaeuser',
    workType: 'Planting',
    location: 'Lewis CO, WA',
    county: 'Lewis',
    state: 'WA',
    crewCount: 0,
    progress: 100,
    totalUnits: 10,
    completedUnits: 10,
    status: 'completed',
    startDate: 'Sep 1, 2025',
    contractValue: 145000,
    bond: 14500,
    bondPaid: true,
    estimatedCompletion: 'Dec 15',
    daysLeft: 0,
    budgetBurn: 100,
    foremanId: 'agustin',
  },
  {
    id: 'banzer',
    name: 'Banzer',
    contractNumber: 'CASCADBZ2025',
    company: 'cascadia',
    landowner: 'Weyerhaeuser',
    workType: 'Planting',
    location: 'Clark CO, WA',
    county: 'Clark',
    state: 'WA',
    crewCount: 0,
    progress: 100,
    totalUnits: 8,
    completedUnits: 8,
    status: 'completed',
    startDate: 'Aug 15, 2025',
    contractValue: 110000,
    bond: 11000,
    bondPaid: true,
    estimatedCompletion: 'Nov 30',
    daysLeft: 0,
    budgetBurn: 100,
    foremanId: 'maya',
  },
  {
    id: 'adams',
    name: 'Adams',
    contractNumber: 'CASCADAD2025',
    company: 'cascadia',
    landowner: 'WA DNR',
    workType: 'Planting',
    location: 'Adams CO, WA',
    county: 'Adams',
    state: 'WA',
    crewCount: 0,
    progress: 100,
    totalUnits: 5,
    completedUnits: 5,
    status: 'completed',
    startDate: 'Jul 1, 2025',
    contractValue: 75000,
    bond: 7500,
    bondPaid: true,
    estimatedCompletion: 'Oct 1',
    daysLeft: 0,
    budgetBurn: 100,
    foremanId: 'agustin',
  },
]

export const employees: Employee[] = [
  {
    id: 'agustin', name: 'Agustin Ramos', initials: 'AR', role: 'foreman', company: 'cascadia',
    rate: 340, rateType: 'daily', hoursThisWeek: 52, otHours: 12, driveHours: 0, h2b: false, active: true,
    compliance: [
      { item: 'DL', expiration: 'Apr 15, 2026', daysLeft: 53, status: 'current' },
      { item: 'CPR', expiration: 'Jun 1, 2026', daysLeft: 100, status: 'current' },
    ],
  },
  {
    id: 'maya', name: 'Maya Torres', initials: 'MT', role: 'foreman', company: 'cascadia',
    rate: 400, rateType: 'daily', hoursThisWeek: 40, otHours: 0, driveHours: 0, h2b: false, active: true,
    compliance: [
      { item: 'DL', expiration: 'May 20, 2026', daysLeft: 88, status: 'current' },
      { item: 'CPR', expiration: 'Jul 15, 2026', daysLeft: 144, status: 'current' },
    ],
  },
  {
    id: 'marco', name: 'Marco Perez', initials: 'MP', role: 'crew', company: 'cascadia',
    rate: 22.0, rateType: 'hourly', hoursThisWeek: 38.5, otHours: 0, driveHours: 8.5, h2b: true, active: true,
    compliance: [
      { item: 'DL', expiration: 'Apr 15, 2026', daysLeft: 53, status: 'current' },
      { item: 'Herbicide License', expiration: 'Feb 28, 2026', daysLeft: 7, status: 'expiring' },
      { item: 'CPR', expiration: 'Jun 1, 2026', daysLeft: 100, status: 'current' },
    ],
  },
  {
    id: 'luis', name: 'Luis Garcia', initials: 'LG', role: 'crew', company: 'cascadia',
    rate: 22.50, rateType: 'hourly', hoursThisWeek: 44, otHours: 4, driveHours: 6.0, h2b: true, active: true,
    compliance: [
      { item: 'DL', expiration: 'Jun 30, 2026', daysLeft: 129, status: 'current' },
    ],
  },
  {
    id: 'elena', name: 'Elena Torres', initials: 'ET', role: 'crew', company: 'cascadia',
    rate: 22.0, rateType: 'hourly', hoursThisWeek: 36.5, otHours: 0, driveHours: 7.0, h2b: true, active: true,
    compliance: [
      { item: 'DL', expiration: 'May 10, 2026', daysLeft: 78, status: 'current' },
    ],
  },
  {
    id: 'diego', name: 'Diego Herrera', initials: 'DH', role: 'driver', company: 'cascadia',
    rate: 23.0, rateType: 'hourly', hoursThisWeek: 51, otHours: 11, driveHours: 38.0, h2b: true, active: true,
    compliance: [
      { item: 'DL', expiration: 'Mar 15, 2026', daysLeft: 22, status: 'expiring' },
    ],
  },
  {
    id: 'carlos', name: 'Carlos Ruiz', initials: 'CR', role: 'driver', company: 'cascadia',
    rate: 23.0, rateType: 'hourly', hoursThisWeek: 50.5, otHours: 10.5, driveHours: 35.0, h2b: true, active: true,
    compliance: [
      { item: 'DL', expiration: 'Mar 15, 2026', daysLeft: 22, status: 'expiring' },
    ],
  },
]

export const timeSheets: TimeSheet[] = [
  { id: 'ts1', date: 'Feb 21', foremanName: 'Agustin Ramos', contractName: 'Vanessa', unit: 'midge u1', crewCount: 11, hours: 0, production: 0, productionUnit: 'trees', otHours: 0, status: 'pending' },
  { id: 'ts2', date: 'Feb 20', foremanName: 'Agustin Ramos', contractName: 'Vanessa', unit: 'quaker u3', crewCount: 12, hours: 96.0, production: 6200, productionUnit: 'trees', otHours: 0, status: 'approved' },
  { id: 'ts3', date: 'Feb 20', foremanName: 'Maya Torres', contractName: 'Kirk', unit: 'silver u1', crewCount: 14, hours: 112.0, production: 8400, productionUnit: 'trees', otHours: 2.5, status: 'approved' },
  { id: 'ts4', date: 'Feb 19', foremanName: 'Agustin Ramos', contractName: 'Vanessa', unit: 'midge u2', crewCount: 12, hours: 94.5, production: 5800, productionUnit: 'trees', otHours: 0, status: 'approved' },
  { id: 'ts5', date: 'Feb 19', foremanName: 'Maya Torres', contractName: 'Kirk', unit: 'kirk u4', crewCount: 14, hours: 108.0, production: 7900, productionUnit: 'trees', otHours: 0, status: 'approved' },
  { id: 'ts6', date: 'Feb 18', foremanName: 'Agustin Ramos', contractName: 'Vanessa', unit: 'midge u1', crewCount: 12, hours: 97.0, production: 6400, productionUnit: 'trees', otHours: 1.0, status: 'approved' },
]

export const alerts: Alert[] = [
  { id: 'a1', type: 'critical', title: 'OSHA 300A Posting', detail: 'Annual posting deadline approaching', countdown: '8 days', module: 'compliance' },
  { id: 'a2', type: 'warning', title: 'Marco Perez — Herbicide License Expiring', detail: 'Renewal required before Feb 28', countdown: '7 days', module: 'crew' },
  { id: 'a3', type: 'warning', title: 'H2B Reimbursements', detail: 'Processing reimbursements for travel', countdown: 'Processing', module: 'payroll' },
  { id: 'a4', type: 'info', title: 'PCT Chainsaw Training', detail: 'Scheduled for next month', countdown: 'April', module: 'safety' },
  { id: 'a5', type: 'success', title: 'FLC/FLCE Renewal', detail: 'Farm Labor Contractor license renewal', countdown: 'June', module: 'compliance' },
]

// Translation keys
export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Sidebar sections
    operations: 'OPERATIONS',
    field: 'FIELD',
    resources: 'RESOURCES',
    compliance_section: 'COMPLIANCE',
    finance: 'FINANCE',
    imports_section: 'IMPORTS',
    admin: 'ADMIN',
    office: 'OFFICE',
    intel: 'INTEL',
    future: 'FUTURE',
    system: 'SYSTEM',
    // Nav items
    overview: 'Overview',
    timeSheets: 'Time Sheets',
    officeTimesheet: 'Submit Timesheet',
    payroll: 'Payroll',
    contracts: 'Projects',
    production: 'Production',
    weather: 'Weather',
    crew: 'Crew',
    crewSets: 'Crew Sets',
    vehicles: 'Vehicles',
    equipment: 'Equipment',
    safetyCerts: 'Safety & Certs',
    calendar: 'Calendar',
    expenses: 'Expenses',
    pendingExpenses: 'Expense Assignments',
    analytics: 'Analytics',
    competitorData: 'Competitor Data',
    bids: 'Bids',
    nurseryOps: 'Nursery Ops',
    contacts: 'Contacts',
    workTracker: 'Work Tracker',
    communications: 'Communications',
    pendingUnits: 'Pending Units',
    adminUnits: 'Units',
    unitIngestAudit: 'Ingest Audit',
    imports: 'Imports',
    // Hub-page tab labels (rendered in topbar by hub wrappers)
    ph_projects: 'Projects',
    ph_units: 'Units',
    eh_expenses: 'Expenses',
    eh_assignments: 'Expense Assignments',
    imp_expenses: 'Expenses',
    imp_units: 'Units',
    imp_other: 'Other Data',
    files: 'Files',
    notifications: 'Notifications',
    settings: 'Settings',
    // Owner
    dashboard: 'Dashboard',
    messages: 'Messages',
    help: 'Help',
    // Foreman
    myContracts: 'My Projects',
    submitTimesheet: 'Submit Timesheet',
    myCrew: 'My Crew',
    vehicleStatus: 'Vehicle Status',
    myHours: 'My Hours',
    // Employee
    myProfile: 'My Profile',
    myDocuments: 'My Documents',
    // General
    activeCrew: 'Active Crew Today',
    weeklyProduction: 'Weekly Production',
    estPayroll: 'Est. Weekly Payroll',
    otRisk: 'OT Risk',
    pendingSheets: 'Pending Sheets',
    activeContracts: 'Active Projects',
    crewOtMonitor: 'Crew OT Monitor',
    driverOtMonitor: 'Driver OT Monitor',
    alertsDeadlines: 'Alerts & Deadlines',
    weatherSnapshot: 'Weather Snapshot',
    viewAll: 'View All',
    reviewNow: 'Review Now',
    live: 'Live',
    allGood: 'All Good',
    needsAttention: 'Needs Attention',
    noIssuesToday: 'No issues today',
    crewsWorkingToday: 'Crews Working Today',
    thisWeekProduction: "This Week's Production",
    payrollThisPeriod: 'Payroll This Period',
    // Payroll page (Batch A — May 2026)
    payroll_summaryView: 'Payroll Summary View',
    payroll_phase2Note: 'Full payroll calculation, export, and period management coming in Phase 2. Current view shows real-time estimates from submitted timesheet data.',
    payroll_currentWeek: 'Current Week',
    payroll_pendingApproval: 'pending approval',
    payroll_estGross: 'Est. Gross',
    payroll_activeWorkers: 'Active Workers',
    payroll_regHours: 'Reg Hours',
    payroll_otHours: 'OT Hours',
    payroll_driveHours: 'Drive Hours',
    payroll_otRiskKpi: 'OT Risk',
    payroll_otClear: 'Clear',
    payroll_otOver: 'over',
    payroll_workerHoursWeek: 'Worker Hours This Week',
    payroll_workersCount: 'workers',
    payroll_colEmployee: 'Employee',
    payroll_colType: 'Type',
    payroll_colWorkHrs: 'Work Hrs',
    payroll_colDriveHrs: 'Drive Hrs',
    payroll_colTotal: 'Total',
    payroll_colStatus: 'Status',
    payroll_typeForeman: 'Foreman',
    payroll_typeDriver: 'Driver',
    payroll_typeCrew: 'Crew',
    payroll_statusOt: 'OT',
    payroll_statusWatch: 'Watch',
    payroll_statusOk: 'OK',
    payroll_footnote: 'Estimates based on avg crew rate $22.50/hr, OT at 1.5x, drive rate $17.13/hr. Actual payroll calculations require approved timesheets and contract-specific rates.',
    // Crew page (Batch A — May 2026)
    crew_contact: 'Contact',
    crew_phone: 'Phone',
    crew_email: 'Email',
    crew_documents: 'Documents & Expirations',
    crew_expired: 'Expired',
    crew_payrollSummary: 'Payroll Summary',
    crew_rate: 'Rate',
    crew_status: 'Status',
    crew_notes: 'Notes',
    crew_loading: 'Loading crew...',
    crew_failedLoad: 'Failed to load crew',
    crew_total: 'Total',
    crew_active: 'Active',
    crew_h2b: 'H2B',
    crew_drivers: 'Drivers',
    crew_foremen: 'Foremen',
    crew_office: 'Office',
    crew_searchPlaceholder: 'Search crew...',
    crew_addEmployee: 'Add Employee',
    crew_noResults: 'No crew members found',
    // Role views (Batch A — May 2026) — owner / foreman / employee dashboards
    rv_contractDetails: 'Contract details',
    rv_loading: 'Loading...',
    rv_loadingProjects: 'Loading projects...',
    rv_loadingContacts: 'Loading contacts...',
    rv_noNewMessages: 'No new messages',
    rv_activeProjects: 'Active Projects',
    rv_crews: 'Crews',
    rv_overallStatus: 'Overall Status',
    rv_languageHeading: 'Language',
    rv_contactHeading: 'Contact',
    rv_supportHeading: 'Support',
    rv_administrator: 'Administrator',
    // Foreman overview tab
    rv_overview: 'Overview',
    rv_unitsInProgress: 'Units In Progress',
    rv_timesheetsCard: 'Timesheets',
    rv_submitTimesheetCard: 'Submit Timesheet',
    rv_newEntry: 'New entry',
    rv_myCrewCard: 'My Crew',
    rv_mapsAndFiles: 'Maps & Files',
    rv_projectDocs: 'Project docs',
    rv_noFavoriteProjects: 'No favorite projects yet',
    rv_goToMyProjects: 'Go to {link} and tap the star to add favorites',
    rv_myProjectsLink: 'My Projects',
    rv_myFavorites: 'My Favorites',
    rv_noFilesYet: 'No files here yet',
    // Project detail
    rv_startDate: 'Start Date',
    rv_endDate: 'End Date',
    rv_workTypes: 'Work Types',
    rv_unitProgress: 'Unit Progress',
    rv_noUnitsConfigured: 'No units configured',
    rv_filesNotSetUp: 'Files not yet set up for this project',
    rv_projectNotes: 'Project Notes',
    rv_noProjectNotes: 'No notes for this project',
    rv_myProjectsHeading: 'My Projects',
    rv_previewOnlyTraining: 'Preview Only — Training in Progress',
    rv_previewExplain: 'This is what timesheet submission will look like. Functionality will be enabled after training.',
    // Expenses placeholders
    rv_expensesHeading: 'Expenses',
    rv_expensesComingSoon: 'Expense tracking and accountability — coming soon.',
    rv_myExpenses: 'My Expenses',
    rv_myExpensesDesc: 'Credit card charges tied to your projects',
    rv_fuelMileage: 'Fuel & Mileage',
    rv_fuelMileageDesc: 'Gas receipts and drive-time reconciliation',
    rv_hotelsLodging: 'Hotels & Lodging',
    rv_hotelsLodgingDesc: 'Accommodation costs per project',
    rv_equipmentPurchases: 'Equipment Purchases',
    rv_equipmentPurchasesDesc: 'Tools, supplies, and gear receipts',
    // Crew sub-tab
    rv_myCrewHeading: 'My Crew',
    rv_hoursLabel: 'Hours',
    rv_rateLabel: 'Rate',
    // Weather sub-tab
    rv_weatherHeading: 'Weather',
    // My Hours
    rv_myHoursHeading: 'My Hours',
    rv_thisWeek: 'This Week',
    rv_driveHoursLabel: 'Drive Hours',
    rv_colDay: 'Day',
    rv_colWorkHours: 'Work Hours',
    rv_colDriveHours: 'Drive Hours',
    rv_colTotal: 'Total',
    // My Profile
    rv_myProfileHeading: 'My Profile',
    rv_companyLabel: 'Company',
    rv_startDateLabel: 'Start Date',
    rv_assignedProjectLabel: 'Assigned Project',
    rv_activeBadge: 'Active',
    // Documents
    rv_myDocsHeading: 'My Documents & Certifications',
    rv_colDocument: 'Document',
    rv_colExpiration: 'Expiration',
    rv_colDaysLeft: 'Days Left',
    rv_colStatus: 'Status',
    // Notifications
    rv_notificationsHeading: 'Notifications',
    rv_genericPlaceholderNote: 'This view shares data with the admin module.',
    rv_calendarTitle: 'Calendar',
    rv_vehicleStatusTitle: 'Vehicle Status',
    // Weather + notification mock prose (will become live data later)
    rv_frostWarning: 'Frost Warning -- Cowlitz CO tomorrow AM, low 28 F',
    rv_windAdvisory: 'Wind Advisory -- Columbia CO Thu-Fri, gusts 25mph',
    rv_crewMemberCompany: 'Crew Member - Cascadia Forestry Inc.',
    rv_notifLicenseExpires: 'Your Herbicide License expires in 7 days. Please renew immediately.',
    rv_notifFrost: 'Frost warning tomorrow morning - dress warmly.',
    // Batch B — Office daily flow (May 2026)
    // Overview page
    ov_loadingContracts: 'Loading contracts...',
    ov_recent: 'Recent',
    ov_loadingOt: 'Loading OT data...',
    ov_noCrewHours: 'No crew hours this week',
    ov_noDriverHours: 'No driver hours this week',
    ov_pendingDecisions: 'Pending Decisions',
    ov_loading: 'Loading…',
    ov_todaysPulse: "Today's Pulse",
    ov_mostRecent7Days: 'Most recent 7 days',
    ov_employeesWorking: 'Employees working',
    ov_thisWeek: 'This week',
    ov_regOtDriveHrs: 'Reg / OT / Drive hrs',
    ov_activeSiteWeather: 'Active Site Weather',
    ov_loadingForecasts: 'Loading forecasts…',
    ov_dailyTrends: 'Daily Trends — last 14 days',
    ov_recentActivity: 'Recent Activity',
    ov_noRecentActivity: 'No recent activity',
    ov_noHoursThisWeek: 'No hours this week',
    ov_crewHoursTitle: 'Crew Hours',
    ov_pendingSheetsTitle: 'Pending Sheets',
    // Timesheets page
    ts_noEntries: 'No entries for this timesheet',
    ts_perEmployeeBreakdown: 'Per-Employee Breakdown',
    ts_colEmployee: 'Employee',
    ts_colRole: 'Role',
    ts_colWorkType: 'Work Type',
    ts_colHours: 'Hours',
    ts_colBags: 'Bags',
    ts_colDriveHrs: 'Drive Hrs',
    ts_colRate: 'Rate',
    ts_colGross: 'Gross',
    ts_totalGross: 'Total Gross',
    ts_loadingTimesheets: 'Loading timesheets...',
    ts_sheetsThisWeek: 'Sheets This Week',
    ts_totalCrewEntries: 'Total Crew Entries',
    ts_pending: 'Pending',
    ts_approved: 'Approved',
    ts_timesheetPhotos: 'Timesheet Photos',
    ts_submittedViaTg: 'Submitted via Telegram by foremen',
    ts_removeFromDashboard: 'Remove from dashboard (does not affect Telegram)',
    ts_colDate: 'Date',
    ts_colForeman: 'Foreman',
    ts_colContract: 'Contract',
    ts_colCrew: 'Crew',
    ts_colStatus: 'Status',
    ts_colActions: 'Actions',
    // Office timesheet entry
    ote_loading: 'Loading...',
    ote_date: 'Date',
    ote_project: 'Project',
    ote_selectProject: 'Select project',
    ote_foreman: 'Foreman',
    ote_selectForeman: 'Select foreman',
    ote_loadCrewSet: 'Load Crew Set',
    ote_quickLoadCrew: 'Quick-load crew',
    ote_shiftStart: 'Shift Start',
    ote_lunchOut: 'Lunch Out',
    ote_lunchIn: 'Lunch In',
    ote_shiftEnd: 'Shift End',
    ote_markAllPresent: 'Mark all present',
    ote_dailyNotes: 'Daily Notes',
    ote_optionalNotes: 'Optional notes about this timesheet...',
    ote_crewPresent: 'Crew Present',
    ote_totalHours: 'Total Hours',
    ote_totalBags: 'Total Bags',
    ote_driveHours: 'Drive Hours',
    ote_treesEst: 'Trees (est)',
    // Pending expenses
    pe_heading: 'Expense Assignments',
    pe_searchPlaceholder: 'Search vendor, cardholder, description, location…',
    pe_colDate: 'Date',
    pe_colVendor: 'Vendor',
    pe_colAmount: 'Amount',
    pe_colCardholder: 'Cardholder',
    pe_colIssue: 'Issue',
    pe_colCategory: 'Category',
    pe_colLocation: 'Location',
    pe_colProject: 'Project',
    pe_deleteBad: 'Delete this bad row',
    pe_allCaughtUp: 'All caught up',
    pe_pendingQueue: 'Pending Queue',
    pe_pickProject: 'Pick a project…',
    pe_deleteBadDup: 'Delete bad/duplicate row',
    // Contacts page
    cp_nameRequired: 'Name *',
    cp_namePlaceholder: 'Jane Smith',
    cp_titleRole: 'Title / Role',
    cp_selectRole: 'Select role...',
    cp_customRolePlaceholder: 'Enter custom role (e.g., COR, COTR, CO)',
    cp_emailLabel: 'Email',
    cp_phoneLabel: 'Phone',
    cp_landownerRequired: 'Landowner *',
    cp_selectLandowner: 'Select landowner...',
    cp_cancel: 'Cancel',
    ts_actionApprove: 'Approve',
    ts_actionReject: 'Reject',
    ts_actionDelete: 'Delete',
    ts_actionView: 'View',
    ts_deleteTimesheetTitle: 'Delete Timesheet',
    // Batch C — Ingest UIs (May 2026)
    // Unit ingest audit
    uia_heading: 'Unit Ingest Audit',
    uia_dryRunTooltip: 'Scan + parse without writing to DB. Useful for sanity checks.',
    uia_runIngestTooltip: 'Scan Drive + parse new files. Writes to unit_ingest_batches and units.',
    uia_retryFailedTooltip: "Flip every 'failed' batch back to 'pending' so the next ingest run picks them up. Non-destructive.",
    uia_wipeTooltip: 'Delete every row in unit_ingest_batches + unit_pending_review + unit_ingest_audit. Asks to confirm.',
    uia_purgeTooltip: "Delete units WHERE name ILIKE '<prefix>%'. Use to clean up TEST UNIT * leftover from fixtures.",
    uia_recentBatches: 'Recent batches',
    uia_recentActivity: 'Recent activity',
    uia_colWhen: 'When',
    uia_colFile: 'File',
    uia_colContract: 'Contract',
    uia_colFormat: 'Format',
    uia_colStatus: 'Status',
    uia_colCreated: 'Created',
    uia_colSkipped: 'Skipped',
    uia_colFlagged: 'Flagged',
    uia_colAction: 'Action',
    uia_colLandowner: 'Landowner',
    uia_colProject: 'Project',
    uia_colUnit: 'Unit',
    uia_colSourceFile: 'Source file',
    uia_colChanges: 'Changes',
    uia_excludesHeading: 'Ingest exclusions',
    uia_allContractsLandowner: 'All contracts under this landowner',
    uia_allUnitsContract: 'All units in this contract',
    uia_pickLandowner: 'Pick a landowner to enable the cascade.',
    uia_colScope: 'Scope',
    uia_colReason: 'Reason',
    uia_colAddedBy: 'Added by',
    uia_colAdded: 'Added',
    uia_removeExclusion: 'Remove exclusion',
    // Pending units
    pu_heading: 'Pending Units',
    pu_allCaughtUp: 'All caught up',
    pu_diffField: 'Field',
    pu_diffCurrent: 'Current',
    pu_diffProposed: 'Proposed',
    pu_provProject: 'Project',
    pu_provInFolder: 'In folder',
    pu_provFile: 'File',
    pu_openProjectFolder: "Open this contract's Drive folder (project root)",
    pu_openFileFolder: "Open the file's actual containing folder",
    pu_openSourceFile: 'Open the source file in Drive',
    pu_lblContract: 'Contract',
    pu_lblNotes: 'Notes',
    // Unit form sheet
    uf_unitNameRequired: 'Unit Name *',
    uf_workType: 'Work Type',
    uf_selectGeneric: 'Select...',
    uf_status: 'Status',
    uf_county: 'County',
    uf_state: 'State',
    uf_amount: 'Amount',
    uf_unitType: 'Unit Type',
    uf_typePlaceholder: 'Type',
    uf_pricePerUnit: 'Price/Unit',
    uf_completionPct: 'Completion %',
    uf_terrain: 'Terrain',
    uf_species: 'Species',
    uf_lblName: 'Name',
    uf_stockType: 'Stock Type',
    uf_count: 'Count',
    uf_location: 'Location',
    uf_latitude: 'Latitude',
    uf_longitude: 'Longitude',
    uf_townshipRangeSection: 'Township / Range / Section',
    uf_targetSpacing: 'Target Spacing',
    uf_stockTypeLegacy: 'Stock Type (legacy)',
    uf_seedlingsPerAcre: 'Seedlings/Acre',
    uf_totalSeedlings: 'Total Seedlings',
    uf_treesPerAcrePlaceholder: 'Trees per acre',
    uf_prescription: 'Prescription',
    uf_elevMin: 'Elev Min (ft)',
    uf_elevMax: 'Elev Max (ft)',
    uf_avgSlope: 'Avg Slope %',
    uf_notes: 'Notes',
    uf_optionalNotes: 'Optional notes...',
    uf_documents: 'Documents',
    uf_download: 'Download',
    uf_remove: 'Remove',
    uf_noDocsYet: 'No documents uploaded yet.',
    // Batch D — Forms (May 2026)
    // Generic form labels (shared across multiple forms)
    form_firstName: 'First Name',
    form_firstNameRequired: 'First Name *',
    form_lastName: 'Last Name',
    form_lastNameRequired: 'Last Name *',
    form_firstNamePlaceholder: 'First name',
    form_lastNamePlaceholder: 'Last name',
    form_phone: 'Phone',
    form_email: 'Email',
    form_company: 'Company',
    form_companyRequired: 'Company *',
    form_status: 'Status',
    form_notes: 'Notes',
    form_name: 'Name',
    form_foreman: 'Foreman',
    form_selectForeman: 'Select foreman...',
    form_selectAll: 'Select All',
    form_clear: 'Clear',
    form_defaultSet: 'Default Set',
    form_rateType: 'Rate Type',
    form_hourlyRate: 'Hourly Rate ($)',
    form_dailyRate: 'Daily Rate ($)',
    // Add employee
    add_emp_title: 'Add Employee',
    // Edit employee
    ed_emp_title: 'Edit Employee',
    ed_emp_passportExp: 'Passport Exp',
    ed_emp_visaExp: 'Visa Exp',
    ed_emp_driveAuthExp: 'Drive Auth Exp',
    ed_emp_herbicideExp: 'Herbicide Exp',
    ed_emp_fingerprintsExp: 'Fingerprints Exp',
    // Create crew set
    cs_title: 'New Crew Set',
    cs_subtitle: 'Create a pre-built crew group for timesheet entry.',
    // Edit crew set
    cse_title: 'Edit Crew Set',
    cse_subtitle: "Update this crew set's name, foreman, or members.",
    // Crew sets list
    crews_noMembers: 'No members',
    crews_lastUsed: 'Last Used',
    crews_defaultSet: 'Default Set',
    crews_loading: 'Loading crew sets...',
    crews_totalSets: 'Total Sets',
    crews_foremenLabel: 'Foremen',
    crews_defaultSets: 'Default Sets',
    crews_deleteConfirm: 'This will remove the crew set and all its member assignments. This cannot be undone.',
    // Edit contract
    ec_title: 'Edit Project',
    ec_status: 'Status',
    ec_projectType: 'Project Type',
    ec_selectType: 'Select type',
    ec_projectNumber: 'Project Number',
    ec_startDate: 'Start Date',
    ec_endDate: 'End Date',
    ec_location: 'Location',
    ec_address: 'Address',
    ec_streetAddress: 'Street address',
    ec_unitType: 'Unit Type',
    ec_typePlaceholder: 'Type',
    ec_seedlings: 'Seedlings',
    ec_acres: 'Acres',
    ec_primeContractor: 'Prime Contractor',
    ec_assignedForeman: 'Assigned Foreman',
    ec_selectForemanOpt: 'Select foreman (optional)',
    ec_none: 'None',
    ec_projectPrice: 'Project Price ($)',
    ec_bondAmount: 'Bond Amount ($)',
    ec_fringeRate: 'Fringe Rate ($/hr)',
    ec_contactName: 'Contact Name',
    // Batch E.1 — smaller pages (May 2026)
    // Weather page
    wp_interactiveMap: 'Interactive Map',
    wp_partlyCloudy: 'Partly Cloudy',
    wp_sprayConditions: 'Spray Conditions',
    wp_fireRiskLevel: 'Fire Risk Level',
    wp_level1NoRestrictions: 'Level 1 — No restrictions',
    wp_noIceWarnings: 'No current ice warnings',
    // Production page
    pp_cumulativeHeading: 'Cumulative Production — All Active Projects',
    pp_dailyOutput: 'Daily Output',
    pp_crewEfficiency: 'Crew Efficiency',
    pp_expectedVsActual: 'Expected vs Actual',
    pp_performanceByUnit: 'Performance by Unit',
    pp_colUnit: 'Unit',
    pp_colContract: 'Contract',
    pp_colTotal: 'Total',
    pp_colDaysWorked: 'Days Worked',
    pp_colAvgDaily: 'Avg Daily',
    pp_colTerrain: 'Terrain',
    pp_colRating: 'Rating',
    // Files page
    fp_openInDrive: 'Open this folder in Google Drive',
    fp_emptyFolder: 'This folder is empty',
    fp_uploadHint: 'Upload files using the button above',
    fp_folders: 'Folders',
    fp_files: 'Files',
    fp_companyFiles: 'Company Files',
    fp_companyFilesDesc: 'Browse and manage company documents organized by category.',
    fp_loadingCategories: 'Loading file categories...',
    fp_operations: 'Operations',
    fp_adminOnly: 'Admin Only',
    fp_projectFiles: 'Project Files',
    fp_projectFilesDesc: 'Maps, specs, and documents for your active projects.',
    fp_noFolder: 'No folder',
    fp_openInDriveGeneric: 'Open in Google Drive',
    // Communications page
    com_heading: 'Communications',
    com_noMessages: 'No messages yet',
    com_sendTooltip: 'Send (Ctrl+Enter)',
    com_deleteTooltip: 'Delete (also removes from Telegram if within 48h)',
    // Calendar page
    cal_less: 'Less',
    cal_more: 'More',
    // Admin units
    au_heading: 'Units',
    au_searchPlaceholder: 'Search by name, county, contract, notes…',
    au_colUnit: 'Unit',
    au_colContract: 'Contract',
    au_colLandowner: 'Landowner',
    au_colAcres: 'Acres',
    au_colLocation: 'Location',
    au_colWork: 'Work',
    au_colStatus: 'Status',
    // Create contract sheet
    cc_title: 'New Project',
    cc_streetAddressPlaceholder: 'Street address — e.g. 123 Timber Rd, Chehalis, WA 98532',
    cc_optionalProjectNotes: 'Additional notes about this project...',
    // Foreman timesheet (Batch E.2)
    ft_loadingContracts: 'Loading contracts...',
    ft_selectContract: 'Select Contract',
    ft_noActiveContracts: 'No active contracts found',
    ft_selectUnits: 'Select Unit(s)',
    ft_loadingUnits: 'Loading units...',
    ft_noUnitsAvailable: 'No units available for this contract yet.',
    ft_contactAdmin: 'Contact your administrator to add units.',
    ft_selectCrew: 'Select Crew',
    ft_loadingCrewSets: 'Loading crew sets...',
    ft_default: 'Default',
    ft_sickInjuredPlaceholder: 'Sick, injured, left early...',
    ft_morning: 'Morning',
    ft_evening: 'Evening',
    ft_start: 'Start',
    ft_end: 'End',
    ft_dailyNotesPlaceholder: 'Daily notes, conditions, issues...',
    ft_voiceToText: 'Voice-to-text',
    ft_bagsLabel: 'Bags',
    ft_unitReviewNotes: 'Unit Review & Notes',
    ft_unitNotesPlaceholder: 'Snow stopped us, finished early, moved to next unit...',
    ft_reviewSubmit: 'Review & Submit',
    ft_summCrew: 'Crew',
    ft_summHours: 'Hours',
    ft_summDrive: 'Drive',
    ft_summBags: 'Bags',
    ft_summTreesPlanted: 'Trees Planted',
    ft_synced: 'Synced',
    ft_offline: 'Offline',
    ft_nextUnitReview: 'Next: Unit Review & Notes',
    ft_nextReview: 'Next: Review',
    ft_loadingCrew: 'Loading crew...',
    ft_noCrewInSet: 'No crew members in this crew set',
    // Batch E.3 + E.4 — contracts.tsx + admin-pages.tsx (May 2026)
    // Contracts page
    cn_noTargetSet: 'No target set',
    cn_invoicedLabel: 'Invoiced',
    cn_paidLabel: 'Paid',
    cn_outstandingLabel: 'Outstanding',
    cn_draft: 'Draft',
    cn_submitted: 'Submitted',
    cn_inspected: 'Inspected',
    cn_approved: 'Approved',
    cn_rejected: 'Rejected',
    cn_descPlaceholder: 'Description',
    cn_acres: 'Acres',
    cn_acresSubmitted: 'Acres Submitted',
    cn_amountInvoiced: 'Amount Invoiced',
    cn_inspectionRequested: 'Inspection Requested',
    cn_inspectionCompleted: 'Inspection Completed',
    cn_inspector: 'Inspector',
    cn_inspectorName: 'Inspector Name',
    cn_paymentReceived: 'Payment Received',
    cn_notesPlaceholder: 'Notes...',
    cn_partialPaymentNotes: 'Optional notes about this partial payment...',
    cn_cancel: 'Cancel',
    cn_editPartialPayment: 'Edit partial payment',
    cn_editUnit: 'Edit unit',
    cn_pendingApproval: 'Pending Approval',
    cn_speciesLabel: 'Species',
    cn_spacingLabel: 'Spacing',
    cn_seedlingsPerAcre: 'Seedlings/acre',
    cn_totalSeedlings: 'Total seedlings',
    cn_stockLabel: 'Stock',
    cn_rxLabel: 'Rx',
    cn_avgSlope: 'Avg slope',
    cn_fireZone: 'Fire zone',
    cn_terrainLabel: 'Terrain',
    cn_elevLabel: 'Elev',
    cn_totalLabel: 'Total',
    cn_completedLabel: 'Completed',
    cn_inProgressLabel: 'In Progress',
    cn_notStartedLabel: 'Not Started',
    cn_avgLabel: 'Avg',
    cn_contactsHeading: 'Contacts',
    cn_contactsDesc: 'People associated with this project',
    cn_namePlaceholder: 'Jane Smith',
    cn_titleRole: 'Title / Role',
    cn_selectRole: 'Select role...',
    cn_customRolePlaceholder: 'Enter custom role (e.g., COR, COTR, CO)',
    cn_noContactsYet: 'No contacts yet',
    cn_addContactsHint: 'Add landowner reps, CORs, inspectors, and other contacts',
    cn_editContact: 'Edit contact',
    cn_deleteContact: 'Delete contact',
    cn_visibleAllRoles: 'Visible to all roles — instructions, site details, reminders',
    cn_notesPlaceholder2: 'Site access instructions, planting specs, foreman reminders, contact info...',
    cn_unsavedChanges: 'Unsaved changes',
    cn_adminOfficeOnly: 'Admin & Office only',
    cn_internalNotesDesc: 'Internal notes — pricing rationale, bid strategy, legal, payroll flags',
    cn_internalNotesPlaceholder: 'Bid notes, pricing rationale, payroll flags, legal reminders, internal decisions...',
    cn_emptyFolder: 'This folder is empty',
    cn_uploadHint: 'Upload files using the button above',
    cn_drivePending: 'Drive folders are being set up for this project',
    cn_drivePendingHint: 'This usually completes within a few seconds of project creation',
    cn_filesInDrive: 'Files are stored in Google Drive — click to open in a new tab',
    cn_noExpensesYet: 'No expenses assigned yet',
    cn_match: 'Match',
    cn_removeFromProject: 'Remove from this project',
    cn_loadingProjects: 'Loading projects...',
    cn_searchPlaceholder: 'Search projects...',
    cn_unassigned: 'Unassigned',
    cn_selectAProject: 'Select a project to view details',
    cn_assignForeman: 'Assign foreman...',
    cn_addToFavorites: "Add this project to the assigned foreman's favorites",
    cn_pendingApproveDesc: 'This project was submitted by a non-admin and needs approval before it goes live.',
    cn_completion: 'Completion',
    cn_unitProgress: 'Unit Progress',
    cn_projectType: 'Project Type',
    cn_productionProgress: 'Production Progress',
    cn_hoursWorked: 'Hours Worked',
    cn_crewLabor: 'Crew Labor',
    cn_driveTime: 'Drive Time',
    cn_hoursByUnit: 'Hours by Unit',
    cn_fringe: 'Fringe',
    cn_prevailingWage: 'Prevailing Wage',
    cn_bond: 'Bond',
    cn_terms: 'Terms',
    cn_searchUnitsPlaceholder: 'Search by name, county, work type…',
    cn_clearSearch: 'Clear search',
    cn_noPayrollYet: 'No payroll data yet',
    cn_byEmployee: 'By employee',
    cn_regHrs: 'Reg hrs',
    cn_driveHrs: 'Drive hrs',
    cn_grossLabel: 'Gross',
    cn_projectDuration: 'Project Duration',
    cn_projectEnded: 'Project ended',
    cn_noDates: 'No dates set for this project',
    cn_keyDates: 'Key Dates',
    cn_projectStart: 'Project Start',
    cn_projectEnd: 'Project End',
    cn_unitsLabel: 'Units',
    cn_unitStatus: 'Unit Status',
    // Admin pages (admin-pages.tsx — 9 sub-pages)
    ap_settings: 'Settings',
    ap_vehicles: 'Vehicles',
    ap_equipment: 'Equipment',
    ap_safetyCerts: 'Safety & Certs',
    ap_expenses: 'Expenses',
    ap_analytics: 'Analytics',
    ap_competitor: 'Competitor Data',
    ap_loadingGeneric: 'Loading...',
    ap_noDataYet: 'No data yet',
    ap_addRecord: 'Add',
    ap_searchPlaceholder: 'Search...',
    ap_save: 'Save',
    ap_cancel: 'Cancel',
    ap_delete: 'Delete',
    ap_edit: 'Edit',
    ap_view: 'View',
    ap_active: 'Active',
    ap_inactive: 'Inactive',
    ap_total: 'Total',
    ap_company: 'Company',
    ap_status: 'Status',
    ap_actions: 'Actions',
    ap_categoryLabel: 'Category',
    ap_amountLabel: 'Amount',
    ap_dateLabel: 'Date',
    ap_yes: 'Yes',
    ap_no: 'No',
  },
  es: {
    operations: 'OPERACIONES',
    field: 'CAMPO',
    resources: 'RECURSOS',
    compliance_section: 'CUMPLIMIENTO',
    finance: 'FINANZAS',
    imports_section: 'IMPORTACIONES',
    admin: 'ADMIN',
    office: 'OFICINA',
    intel: 'INTELIGENCIA',
    future: 'FUTURO',
    system: 'SISTEMA',
    overview: 'Resumen',
    timeSheets: 'Hojas de Tiempo',
    officeTimesheet: 'Enviar Hoja de Tiempo',
    payroll: 'Nomina',
    contracts: 'Proyectos',
    production: 'Produccion',
    weather: 'Clima',
    crew: 'Equipo',
    crewSets: 'Grupos de Equipo',
    vehicles: 'Vehiculos',
    equipment: 'Herramientas',
    safetyCerts: 'Seguridad y Certs',
    calendar: 'Calendario',
    expenses: 'Gastos',
    pendingExpenses: 'Asignar Gastos',
    analytics: 'Analitica',
    competitorData: 'Datos Competidores',
    bids: 'Licitaciones',
    nurseryOps: 'Viveros',
    contacts: 'Contactos',
    workTracker: 'Seguimiento',
    communications: 'Comunicaciones',
    pendingUnits: 'Unidades Pendientes',
    adminUnits: 'Unidades',
    unitIngestAudit: 'Auditoría Ingreso',
    imports: 'Importaciones',
    // Hub-page tab labels
    ph_projects: 'Proyectos',
    ph_units: 'Unidades',
    eh_expenses: 'Gastos',
    eh_assignments: 'Asignar Gastos',
    imp_expenses: 'Gastos',
    imp_units: 'Unidades',
    imp_other: 'Otros Datos',
    files: 'Archivos',
    notifications: 'Notificaciones',
    settings: 'Configuracion',
    dashboard: 'Panel',
    messages: 'Mensajes',
    help: 'Ayuda',
    myContracts: 'Mis Proyectos',
    submitTimesheet: 'Enviar Hoja de Tiempo',
    myCrew: 'Mi Equipo',
    vehicleStatus: 'Estado del Vehiculo',
    myHours: 'Mis Horas',
    myProfile: 'Mi Perfil',
    myDocuments: 'Mis Documentos',
    activeCrew: 'Equipo Activo Hoy',
    weeklyProduction: 'Produccion Semanal',
    estPayroll: 'Nomina Semanal Est.',
    otRisk: 'Riesgo OT',
    pendingSheets: 'Hojas Pendientes',
    activeContracts: 'Proyectos Activos',
    crewOtMonitor: 'Monitor OT Equipo',
    driverOtMonitor: 'Monitor OT Conductores',
    alertsDeadlines: 'Alertas y Fechas Limite',
    weatherSnapshot: 'Clima Resumen',
    viewAll: 'Ver Todo',
    reviewNow: 'Revisar Ahora',
    live: 'En Vivo',
    allGood: 'Todo Bien',
    needsAttention: 'Necesita Atencion',
    noIssuesToday: 'Sin problemas hoy',
    crewsWorkingToday: 'Equipos Trabajando Hoy',
    thisWeekProduction: 'Produccion de Esta Semana',
    payrollThisPeriod: 'Nomina Este Periodo',
    // Payroll page (Batch A — May 2026)
    payroll_summaryView: 'Resumen de Nómina',
    payroll_phase2Note: 'Cálculo completo de nómina, exportación y gestión de períodos próximamente en Fase 2. La vista actual muestra estimaciones en tiempo real de hojas de tiempo enviadas.',
    payroll_currentWeek: 'Semana Actual',
    payroll_pendingApproval: 'pendiente de aprobación',
    payroll_estGross: 'Bruto Est.',
    payroll_activeWorkers: 'Trabajadores Activos',
    payroll_regHours: 'Horas Reg.',
    payroll_otHours: 'Horas OT',
    payroll_driveHours: 'Horas Manejo',
    payroll_otRiskKpi: 'Riesgo OT',
    payroll_otClear: 'Sin Riesgo',
    payroll_otOver: 'sobre',
    payroll_workerHoursWeek: 'Horas Trabajadores Esta Semana',
    payroll_workersCount: 'trabajadores',
    payroll_colEmployee: 'Empleado',
    payroll_colType: 'Tipo',
    payroll_colWorkHrs: 'Hrs. Trabajo',
    payroll_colDriveHrs: 'Hrs. Manejo',
    payroll_colTotal: 'Total',
    payroll_colStatus: 'Estado',
    payroll_typeForeman: 'Capataz',
    payroll_typeDriver: 'Conductor',
    payroll_typeCrew: 'Equipo',
    payroll_statusOt: 'OT',
    payroll_statusWatch: 'Vigilar',
    payroll_statusOk: 'OK',
    payroll_footnote: 'Estimaciones basadas en tarifa promedio de equipo $22.50/hr, OT a 1.5x, tarifa de manejo $17.13/hr. Los cálculos reales de nómina requieren hojas de tiempo aprobadas y tarifas específicas del contrato.',
    // Crew page (Batch A — May 2026)
    crew_contact: 'Contacto',
    crew_phone: 'Teléfono',
    crew_email: 'Correo',
    crew_documents: 'Documentos y Vencimientos',
    crew_expired: 'Vencido',
    crew_payrollSummary: 'Resumen de Nómina',
    crew_rate: 'Tarifa',
    crew_status: 'Estado',
    crew_notes: 'Notas',
    crew_loading: 'Cargando equipo...',
    crew_failedLoad: 'Error al cargar el equipo',
    crew_total: 'Total',
    crew_active: 'Activos',
    crew_h2b: 'H2B',
    crew_drivers: 'Conductores',
    crew_foremen: 'Capataces',
    crew_office: 'Oficina',
    crew_searchPlaceholder: 'Buscar equipo...',
    crew_addEmployee: 'Agregar Empleado',
    crew_noResults: 'No se encontraron miembros',
    // Role views (Batch A — May 2026) — vista de propietario / capataz / empleado
    // Owner-view labels were already Spanish-only; now wrapped so EN-toggle
    // shows English equivalents to non-Jose admins.
    rv_contractDetails: 'Detalles del contrato',
    rv_loading: 'Cargando...',
    rv_loadingProjects: 'Cargando proyectos...',
    rv_loadingContacts: 'Cargando contactos...',
    rv_noNewMessages: 'No hay mensajes nuevos',
    rv_activeProjects: 'Proyectos Activos',
    rv_crews: 'Cuadrillas',
    rv_overallStatus: 'Estado General',
    rv_languageHeading: 'Idioma',
    rv_contactHeading: 'Contacto',
    rv_supportHeading: 'Soporte',
    rv_administrator: 'Administrador',
    // Foreman overview tab
    rv_overview: 'Resumen',
    rv_unitsInProgress: 'Unidades en Progreso',
    rv_timesheetsCard: 'Hojas de Tiempo',
    rv_submitTimesheetCard: 'Enviar Hoja de Tiempo',
    rv_newEntry: 'Nueva entrada',
    rv_myCrewCard: 'Mi Equipo',
    rv_mapsAndFiles: 'Mapas y Archivos',
    rv_projectDocs: 'Documentos del proyecto',
    rv_noFavoriteProjects: 'Aún no hay proyectos favoritos',
    rv_goToMyProjects: 'Ve a {link} y toca la estrella para agregar favoritos',
    rv_myProjectsLink: 'Mis Proyectos',
    rv_myFavorites: 'Mis Favoritos',
    rv_noFilesYet: 'Aún no hay archivos aquí',
    // Project detail
    rv_startDate: 'Fecha de Inicio',
    rv_endDate: 'Fecha de Fin',
    rv_workTypes: 'Tipos de Trabajo',
    rv_unitProgress: 'Progreso de Unidades',
    rv_noUnitsConfigured: 'Sin unidades configuradas',
    rv_filesNotSetUp: 'Archivos aún no configurados para este proyecto',
    rv_projectNotes: 'Notas del Proyecto',
    rv_noProjectNotes: 'No hay notas para este proyecto',
    rv_myProjectsHeading: 'Mis Proyectos',
    rv_previewOnlyTraining: 'Solo Vista Previa — Entrenamiento en Progreso',
    rv_previewExplain: 'Así se verá el envío de hojas de tiempo. La funcionalidad se habilitará después del entrenamiento.',
    // Expenses placeholders
    rv_expensesHeading: 'Gastos',
    rv_expensesComingSoon: 'Seguimiento y rendición de gastos — próximamente.',
    rv_myExpenses: 'Mis Gastos',
    rv_myExpensesDesc: 'Cargos de tarjeta vinculados a sus proyectos',
    rv_fuelMileage: 'Combustible y Kilometraje',
    rv_fuelMileageDesc: 'Recibos de gasolina y reconciliación de tiempo de manejo',
    rv_hotelsLodging: 'Hoteles y Alojamiento',
    rv_hotelsLodgingDesc: 'Costos de alojamiento por proyecto',
    rv_equipmentPurchases: 'Compras de Equipo',
    rv_equipmentPurchasesDesc: 'Recibos de herramientas, suministros y equipo',
    // Crew sub-tab
    rv_myCrewHeading: 'Mi Equipo',
    rv_hoursLabel: 'Horas',
    rv_rateLabel: 'Tarifa',
    // Weather sub-tab
    rv_weatherHeading: 'Clima',
    // My Hours
    rv_myHoursHeading: 'Mis Horas',
    rv_thisWeek: 'Esta Semana',
    rv_driveHoursLabel: 'Horas de Manejo',
    rv_colDay: 'Día',
    rv_colWorkHours: 'Horas de Trabajo',
    rv_colDriveHours: 'Horas de Manejo',
    rv_colTotal: 'Total',
    // My Profile
    rv_myProfileHeading: 'Mi Perfil',
    rv_companyLabel: 'Empresa',
    rv_startDateLabel: 'Fecha de Inicio',
    rv_assignedProjectLabel: 'Proyecto Asignado',
    rv_activeBadge: 'Activo',
    // Documents
    rv_myDocsHeading: 'Mis Documentos y Certificaciones',
    rv_colDocument: 'Documento',
    rv_colExpiration: 'Vencimiento',
    rv_colDaysLeft: 'Días Restantes',
    rv_colStatus: 'Estado',
    // Notifications
    rv_notificationsHeading: 'Notificaciones',
    rv_genericPlaceholderNote: 'Esta vista comparte datos con el módulo de administración.',
    rv_calendarTitle: 'Calendario',
    rv_vehicleStatusTitle: 'Estado del Vehículo',
    // Weather + notification mock prose
    rv_frostWarning: 'Alerta de Heladas -- Condado de Cowlitz mañana AM, mínima 28 F',
    rv_windAdvisory: 'Aviso de Viento -- Condado de Columbia jueves-viernes, ráfagas 25mph',
    rv_crewMemberCompany: 'Miembro del Equipo - Cascadia Forestry Inc.',
    rv_notifLicenseExpires: 'Su Licencia de Herbicida vence en 7 días. Por favor renovarla de inmediato.',
    rv_notifFrost: 'Alerta de heladas mañana en la mañana - vestirse abrigado.',
    // Batch B — Office daily flow (May 2026)
    // Overview page
    ov_loadingContracts: 'Cargando proyectos...',
    ov_recent: 'Reciente',
    ov_loadingOt: 'Cargando datos OT...',
    ov_noCrewHours: 'Sin horas de equipo esta semana',
    ov_noDriverHours: 'Sin horas de conductores esta semana',
    ov_pendingDecisions: 'Decisiones Pendientes',
    ov_loading: 'Cargando…',
    ov_todaysPulse: 'Pulso de Hoy',
    ov_mostRecent7Days: 'Últimos 7 días',
    ov_employeesWorking: 'Empleados trabajando',
    ov_thisWeek: 'Esta semana',
    ov_regOtDriveHrs: 'Hrs Reg / OT / Manejo',
    ov_activeSiteWeather: 'Clima en Sitios Activos',
    ov_loadingForecasts: 'Cargando pronósticos…',
    ov_dailyTrends: 'Tendencias Diarias — últimos 14 días',
    ov_recentActivity: 'Actividad Reciente',
    ov_noRecentActivity: 'Sin actividad reciente',
    ov_noHoursThisWeek: 'Sin horas esta semana',
    ov_crewHoursTitle: 'Horas de Equipo',
    ov_pendingSheetsTitle: 'Hojas Pendientes',
    // Timesheets page
    ts_noEntries: 'Sin entradas para esta hoja de tiempo',
    ts_perEmployeeBreakdown: 'Desglose por Empleado',
    ts_colEmployee: 'Empleado',
    ts_colRole: 'Rol',
    ts_colWorkType: 'Tipo de Trabajo',
    ts_colHours: 'Horas',
    ts_colBags: 'Bolsas',
    ts_colDriveHrs: 'Hrs. Manejo',
    ts_colRate: 'Tarifa',
    ts_colGross: 'Bruto',
    ts_totalGross: 'Bruto Total',
    ts_loadingTimesheets: 'Cargando hojas de tiempo...',
    ts_sheetsThisWeek: 'Hojas Esta Semana',
    ts_totalCrewEntries: 'Total Entradas de Equipo',
    ts_pending: 'Pendientes',
    ts_approved: 'Aprobadas',
    ts_timesheetPhotos: 'Fotos de Hojas de Tiempo',
    ts_submittedViaTg: 'Enviadas vía Telegram por capataces',
    ts_removeFromDashboard: 'Quitar del panel (no afecta Telegram)',
    ts_colDate: 'Fecha',
    ts_colForeman: 'Capataz',
    ts_colContract: 'Contrato',
    ts_colCrew: 'Equipo',
    ts_colStatus: 'Estado',
    ts_colActions: 'Acciones',
    // Office timesheet entry
    ote_loading: 'Cargando...',
    ote_date: 'Fecha',
    ote_project: 'Proyecto',
    ote_selectProject: 'Seleccionar proyecto',
    ote_foreman: 'Capataz',
    ote_selectForeman: 'Seleccionar capataz',
    ote_loadCrewSet: 'Cargar Grupo',
    ote_quickLoadCrew: 'Cargar equipo rápido',
    ote_shiftStart: 'Inicio de Turno',
    ote_lunchOut: 'Salida Almuerzo',
    ote_lunchIn: 'Regreso Almuerzo',
    ote_shiftEnd: 'Fin de Turno',
    ote_markAllPresent: 'Marcar todos presentes',
    ote_dailyNotes: 'Notas Diarias',
    ote_optionalNotes: 'Notas opcionales sobre esta hoja de tiempo...',
    ote_crewPresent: 'Equipo Presente',
    ote_totalHours: 'Horas Totales',
    ote_totalBags: 'Bolsas Totales',
    ote_driveHours: 'Horas de Manejo',
    ote_treesEst: 'Árboles (est)',
    // Pending expenses
    pe_heading: 'Asignación de Gastos',
    pe_searchPlaceholder: 'Buscar proveedor, titular, descripción, ubicación…',
    pe_colDate: 'Fecha',
    pe_colVendor: 'Proveedor',
    pe_colAmount: 'Monto',
    pe_colCardholder: 'Titular',
    pe_colIssue: 'Problema',
    pe_colCategory: 'Categoría',
    pe_colLocation: 'Ubicación',
    pe_colProject: 'Proyecto',
    pe_deleteBad: 'Eliminar fila incorrecta',
    pe_allCaughtUp: 'Todo al día',
    pe_pendingQueue: 'Cola Pendiente',
    pe_pickProject: 'Elegir un proyecto…',
    pe_deleteBadDup: 'Eliminar fila incorrecta/duplicada',
    // Contacts page
    cp_nameRequired: 'Nombre *',
    cp_namePlaceholder: 'Juan Pérez',
    cp_titleRole: 'Título / Rol',
    cp_selectRole: 'Seleccionar rol...',
    cp_customRolePlaceholder: 'Ingresar rol personalizado (ej. COR, COTR, CO)',
    cp_emailLabel: 'Correo',
    cp_phoneLabel: 'Teléfono',
    cp_landownerRequired: 'Propietario *',
    cp_selectLandowner: 'Seleccionar propietario...',
    cp_cancel: 'Cancelar',
    ts_actionApprove: 'Aprobar',
    ts_actionReject: 'Rechazar',
    ts_actionDelete: 'Eliminar',
    ts_actionView: 'Ver',
    ts_deleteTimesheetTitle: 'Eliminar Hoja de Tiempo',
    // Batch C — Ingest UIs (May 2026)
    uia_heading: 'Auditoría de Ingreso de Unidades',
    uia_dryRunTooltip: 'Escanear y analizar sin escribir en la BD. Útil para verificación.',
    uia_runIngestTooltip: 'Escanear Drive y analizar archivos nuevos. Escribe en unit_ingest_batches y units.',
    uia_retryFailedTooltip: "Cambiar cada lote 'failed' a 'pending' para que el siguiente ingreso los procese. No destructivo.",
    uia_wipeTooltip: 'Eliminar todas las filas en unit_ingest_batches + unit_pending_review + unit_ingest_audit. Pide confirmación.',
    uia_purgeTooltip: "Eliminar units WHERE name ILIKE '<prefix>%'. Para limpiar TEST UNIT * de fixtures.",
    uia_recentBatches: 'Lotes Recientes',
    uia_recentActivity: 'Actividad Reciente',
    uia_colWhen: 'Cuándo',
    uia_colFile: 'Archivo',
    uia_colContract: 'Contrato',
    uia_colFormat: 'Formato',
    uia_colStatus: 'Estado',
    uia_colCreated: 'Creadas',
    uia_colSkipped: 'Omitidas',
    uia_colFlagged: 'Marcadas',
    uia_colAction: 'Acción',
    uia_colLandowner: 'Propietario',
    uia_colProject: 'Proyecto',
    uia_colUnit: 'Unidad',
    uia_colSourceFile: 'Archivo Fuente',
    uia_colChanges: 'Cambios',
    uia_excludesHeading: 'Exclusiones de Ingreso',
    uia_allContractsLandowner: 'Todos los contratos de este propietario',
    uia_allUnitsContract: 'Todas las unidades en este contrato',
    uia_pickLandowner: 'Elegir un propietario para habilitar la cascada.',
    uia_colScope: 'Alcance',
    uia_colReason: 'Razón',
    uia_colAddedBy: 'Agregado por',
    uia_colAdded: 'Agregado',
    uia_removeExclusion: 'Quitar exclusión',
    // Pending units
    pu_heading: 'Unidades Pendientes',
    pu_allCaughtUp: 'Todo al día',
    pu_diffField: 'Campo',
    pu_diffCurrent: 'Actual',
    pu_diffProposed: 'Propuesto',
    pu_provProject: 'Proyecto',
    pu_provInFolder: 'En carpeta',
    pu_provFile: 'Archivo',
    pu_openProjectFolder: 'Abrir la carpeta de Drive de este contrato (raíz del proyecto)',
    pu_openFileFolder: 'Abrir la carpeta contenedora real del archivo',
    pu_openSourceFile: 'Abrir el archivo fuente en Drive',
    pu_lblContract: 'Contrato',
    pu_lblNotes: 'Notas',
    // Unit form sheet
    uf_unitNameRequired: 'Nombre de Unidad *',
    uf_workType: 'Tipo de Trabajo',
    uf_selectGeneric: 'Seleccionar...',
    uf_status: 'Estado',
    uf_county: 'Condado',
    uf_state: 'Estado',
    uf_amount: 'Cantidad',
    uf_unitType: 'Tipo de Unidad',
    uf_typePlaceholder: 'Tipo',
    uf_pricePerUnit: 'Precio/Unidad',
    uf_completionPct: '% Completado',
    uf_terrain: 'Terreno',
    uf_species: 'Especies',
    uf_lblName: 'Nombre',
    uf_stockType: 'Tipo de Stock',
    uf_count: 'Cantidad',
    uf_location: 'Ubicación',
    uf_latitude: 'Latitud',
    uf_longitude: 'Longitud',
    uf_townshipRangeSection: 'Township / Range / Section',
    uf_targetSpacing: 'Espaciado Objetivo',
    uf_stockTypeLegacy: 'Tipo de Stock (legacy)',
    uf_seedlingsPerAcre: 'Plántulas/Acre',
    uf_totalSeedlings: 'Plántulas Totales',
    uf_treesPerAcrePlaceholder: 'Árboles por acre',
    uf_prescription: 'Prescripción',
    uf_elevMin: 'Elev Mín (pies)',
    uf_elevMax: 'Elev Máx (pies)',
    uf_avgSlope: '% Pendiente Prom',
    uf_notes: 'Notas',
    uf_optionalNotes: 'Notas opcionales...',
    uf_documents: 'Documentos',
    uf_download: 'Descargar',
    uf_remove: 'Quitar',
    uf_noDocsYet: 'Aún no se han subido documentos.',
    // Batch D — Forms (May 2026)
    form_firstName: 'Nombre',
    form_firstNameRequired: 'Nombre *',
    form_lastName: 'Apellido',
    form_lastNameRequired: 'Apellido *',
    form_firstNamePlaceholder: 'Nombre',
    form_lastNamePlaceholder: 'Apellido',
    form_phone: 'Teléfono',
    form_email: 'Correo',
    form_company: 'Empresa',
    form_companyRequired: 'Empresa *',
    form_status: 'Estado',
    form_notes: 'Notas',
    form_name: 'Nombre',
    form_foreman: 'Capataz',
    form_selectForeman: 'Seleccionar capataz...',
    form_selectAll: 'Seleccionar Todos',
    form_clear: 'Limpiar',
    form_defaultSet: 'Grupo Predeterminado',
    form_rateType: 'Tipo de Tarifa',
    form_hourlyRate: 'Tarifa por Hora ($)',
    form_dailyRate: 'Tarifa Diaria ($)',
    add_emp_title: 'Agregar Empleado',
    ed_emp_title: 'Editar Empleado',
    ed_emp_passportExp: 'Venc. Pasaporte',
    ed_emp_visaExp: 'Venc. Visa',
    ed_emp_driveAuthExp: 'Venc. Aut. Manejo',
    ed_emp_herbicideExp: 'Venc. Herbicida',
    ed_emp_fingerprintsExp: 'Venc. Huellas',
    cs_title: 'Nuevo Grupo',
    cs_subtitle: 'Crear un grupo de equipo prearmado para entrada de hojas de tiempo.',
    cse_title: 'Editar Grupo',
    cse_subtitle: 'Actualizar el nombre, capataz o miembros de este grupo.',
    crews_noMembers: 'Sin miembros',
    crews_lastUsed: 'Último Uso',
    crews_defaultSet: 'Grupo Predeterminado',
    crews_loading: 'Cargando grupos...',
    crews_totalSets: 'Grupos Totales',
    crews_foremenLabel: 'Capataces',
    crews_defaultSets: 'Grupos Predeterminados',
    crews_deleteConfirm: 'Esto eliminará el grupo y todas las asignaciones de miembros. No se puede deshacer.',
    ec_title: 'Editar Proyecto',
    ec_status: 'Estado',
    ec_projectType: 'Tipo de Proyecto',
    ec_selectType: 'Seleccionar tipo',
    ec_projectNumber: 'Número de Proyecto',
    ec_startDate: 'Fecha de Inicio',
    ec_endDate: 'Fecha de Fin',
    ec_location: 'Ubicación',
    ec_address: 'Dirección',
    ec_streetAddress: 'Dirección postal',
    ec_unitType: 'Tipo de Unidad',
    ec_typePlaceholder: 'Tipo',
    ec_seedlings: 'Plántulas',
    ec_acres: 'Acres',
    ec_primeContractor: 'Contratista Principal',
    ec_assignedForeman: 'Capataz Asignado',
    ec_selectForemanOpt: 'Seleccionar capataz (opcional)',
    ec_none: 'Ninguno',
    ec_projectPrice: 'Precio del Proyecto ($)',
    ec_bondAmount: 'Monto de Fianza ($)',
    ec_fringeRate: 'Tarifa Fringe ($/hr)',
    ec_contactName: 'Nombre de Contacto',
    // Batch E.1 — smaller pages (May 2026)
    wp_interactiveMap: 'Mapa Interactivo',
    wp_partlyCloudy: 'Parcialmente Nublado',
    wp_sprayConditions: 'Condiciones para Aspersión',
    wp_fireRiskLevel: 'Nivel de Riesgo de Incendio',
    wp_level1NoRestrictions: 'Nivel 1 — Sin restricciones',
    wp_noIceWarnings: 'Sin alertas de hielo actuales',
    pp_cumulativeHeading: 'Producción Acumulada — Todos los Proyectos Activos',
    pp_dailyOutput: 'Producción Diaria',
    pp_crewEfficiency: 'Eficiencia del Equipo',
    pp_expectedVsActual: 'Esperado vs Real',
    pp_performanceByUnit: 'Desempeño por Unidad',
    pp_colUnit: 'Unidad',
    pp_colContract: 'Contrato',
    pp_colTotal: 'Total',
    pp_colDaysWorked: 'Días Trabajados',
    pp_colAvgDaily: 'Promedio Diario',
    pp_colTerrain: 'Terreno',
    pp_colRating: 'Calificación',
    fp_openInDrive: 'Abrir esta carpeta en Google Drive',
    fp_emptyFolder: 'Esta carpeta está vacía',
    fp_uploadHint: 'Subir archivos usando el botón de arriba',
    fp_folders: 'Carpetas',
    fp_files: 'Archivos',
    fp_companyFiles: 'Archivos de la Empresa',
    fp_companyFilesDesc: 'Explorar y gestionar documentos de la empresa organizados por categoría.',
    fp_loadingCategories: 'Cargando categorías...',
    fp_operations: 'Operaciones',
    fp_adminOnly: 'Solo Admin',
    fp_projectFiles: 'Archivos del Proyecto',
    fp_projectFilesDesc: 'Mapas, especificaciones y documentos para sus proyectos activos.',
    fp_noFolder: 'Sin carpeta',
    fp_openInDriveGeneric: 'Abrir en Google Drive',
    com_heading: 'Comunicaciones',
    com_noMessages: 'Aún no hay mensajes',
    com_sendTooltip: 'Enviar (Ctrl+Enter)',
    com_deleteTooltip: 'Eliminar (también quita de Telegram si dentro de 48h)',
    cal_less: 'Menos',
    cal_more: 'Más',
    au_heading: 'Unidades',
    au_searchPlaceholder: 'Buscar por nombre, condado, contrato, notas…',
    au_colUnit: 'Unidad',
    au_colContract: 'Contrato',
    au_colLandowner: 'Propietario',
    au_colAcres: 'Acres',
    au_colLocation: 'Ubicación',
    au_colWork: 'Trabajo',
    au_colStatus: 'Estado',
    cc_title: 'Nuevo Proyecto',
    cc_streetAddressPlaceholder: 'Dirección postal — ej. 123 Timber Rd, Chehalis, WA 98532',
    cc_optionalProjectNotes: 'Notas adicionales sobre este proyecto...',
    // Foreman timesheet (Batch E.2)
    ft_loadingContracts: 'Cargando proyectos...',
    ft_selectContract: 'Seleccionar Proyecto',
    ft_noActiveContracts: 'No se encontraron proyectos activos',
    ft_selectUnits: 'Seleccionar Unidad(es)',
    ft_loadingUnits: 'Cargando unidades...',
    ft_noUnitsAvailable: 'Aún no hay unidades disponibles para este proyecto.',
    ft_contactAdmin: 'Contactar al administrador para agregar unidades.',
    ft_selectCrew: 'Seleccionar Equipo',
    ft_loadingCrewSets: 'Cargando grupos...',
    ft_default: 'Predeterminado',
    ft_sickInjuredPlaceholder: 'Enfermo, lesionado, salió temprano...',
    ft_morning: 'Mañana',
    ft_evening: 'Tarde',
    ft_start: 'Inicio',
    ft_end: 'Fin',
    ft_dailyNotesPlaceholder: 'Notas diarias, condiciones, problemas...',
    ft_voiceToText: 'Voz a texto',
    ft_bagsLabel: 'Bolsas',
    ft_unitReviewNotes: 'Revisión de Unidades y Notas',
    ft_unitNotesPlaceholder: 'Nieve nos detuvo, terminamos temprano, pasamos a la siguiente unidad...',
    ft_reviewSubmit: 'Revisar y Enviar',
    ft_summCrew: 'Equipo',
    ft_summHours: 'Horas',
    ft_summDrive: 'Manejo',
    ft_summBags: 'Bolsas',
    ft_summTreesPlanted: 'Árboles Plantados',
    ft_synced: 'Sincronizado',
    ft_offline: 'Sin conexión',
    ft_nextUnitReview: 'Siguiente: Revisión de Unidades y Notas',
    ft_nextReview: 'Siguiente: Revisar',
    ft_loadingCrew: 'Cargando equipo...',
    ft_noCrewInSet: 'No hay miembros en este grupo',
    // Batch E.3 + E.4 — contracts.tsx + admin-pages.tsx
    cn_noTargetSet: 'Sin objetivo establecido',
    cn_invoicedLabel: 'Facturado',
    cn_paidLabel: 'Pagado',
    cn_outstandingLabel: 'Pendiente',
    cn_draft: 'Borrador',
    cn_submitted: 'Enviado',
    cn_inspected: 'Inspeccionado',
    cn_approved: 'Aprobado',
    cn_rejected: 'Rechazado',
    cn_descPlaceholder: 'Descripción',
    cn_acres: 'Acres',
    cn_acresSubmitted: 'Acres Enviados',
    cn_amountInvoiced: 'Monto Facturado',
    cn_inspectionRequested: 'Inspección Solicitada',
    cn_inspectionCompleted: 'Inspección Completada',
    cn_inspector: 'Inspector',
    cn_inspectorName: 'Nombre del Inspector',
    cn_paymentReceived: 'Pago Recibido',
    cn_notesPlaceholder: 'Notas...',
    cn_partialPaymentNotes: 'Notas opcionales sobre este pago parcial...',
    cn_cancel: 'Cancelar',
    cn_editPartialPayment: 'Editar pago parcial',
    cn_editUnit: 'Editar unidad',
    cn_pendingApproval: 'Pendiente de Aprobación',
    cn_speciesLabel: 'Especies',
    cn_spacingLabel: 'Espaciado',
    cn_seedlingsPerAcre: 'Plántulas/acre',
    cn_totalSeedlings: 'Plántulas totales',
    cn_stockLabel: 'Stock',
    cn_rxLabel: 'Rx',
    cn_avgSlope: 'Pendiente prom.',
    cn_fireZone: 'Zona de fuego',
    cn_terrainLabel: 'Terreno',
    cn_elevLabel: 'Elev',
    cn_totalLabel: 'Total',
    cn_completedLabel: 'Completado',
    cn_inProgressLabel: 'En Progreso',
    cn_notStartedLabel: 'Sin Iniciar',
    cn_avgLabel: 'Prom',
    cn_contactsHeading: 'Contactos',
    cn_contactsDesc: 'Personas asociadas con este proyecto',
    cn_namePlaceholder: 'Juan Pérez',
    cn_titleRole: 'Título / Rol',
    cn_selectRole: 'Seleccionar rol...',
    cn_customRolePlaceholder: 'Ingresar rol personalizado (ej. COR, COTR, CO)',
    cn_noContactsYet: 'Aún no hay contactos',
    cn_addContactsHint: 'Agregar representantes del propietario, CORs, inspectores y otros contactos',
    cn_editContact: 'Editar contacto',
    cn_deleteContact: 'Eliminar contacto',
    cn_visibleAllRoles: 'Visible para todos los roles — instrucciones, detalles del sitio, recordatorios',
    cn_notesPlaceholder2: 'Instrucciones de acceso al sitio, especificaciones de plantación, recordatorios para el capataz, info de contacto...',
    cn_unsavedChanges: 'Cambios sin guardar',
    cn_adminOfficeOnly: 'Solo Admin y Oficina',
    cn_internalNotesDesc: 'Notas internas — justificación de precios, estrategia de oferta, legal, marcas de nómina',
    cn_internalNotesPlaceholder: 'Notas de oferta, justificación de precios, marcas de nómina, recordatorios legales, decisiones internas...',
    cn_emptyFolder: 'Esta carpeta está vacía',
    cn_uploadHint: 'Subir archivos usando el botón de arriba',
    cn_drivePending: 'Las carpetas de Drive se están configurando para este proyecto',
    cn_drivePendingHint: 'Esto normalmente se completa en unos segundos después de crear el proyecto',
    cn_filesInDrive: 'Los archivos están en Google Drive — clic para abrir en una nueva pestaña',
    cn_noExpensesYet: 'Aún no hay gastos asignados',
    cn_match: 'Coincidencia',
    cn_removeFromProject: 'Quitar de este proyecto',
    cn_loadingProjects: 'Cargando proyectos...',
    cn_searchPlaceholder: 'Buscar proyectos...',
    cn_unassigned: 'Sin asignar',
    cn_selectAProject: 'Seleccione un proyecto para ver los detalles',
    cn_assignForeman: 'Asignar capataz...',
    cn_addToFavorites: 'Agregar este proyecto a los favoritos del capataz asignado',
    cn_pendingApproveDesc: 'Este proyecto fue enviado por un usuario no admin y necesita aprobación antes de activarse.',
    cn_completion: 'Finalización',
    cn_unitProgress: 'Progreso de Unidades',
    cn_projectType: 'Tipo de Proyecto',
    cn_productionProgress: 'Progreso de Producción',
    cn_hoursWorked: 'Horas Trabajadas',
    cn_crewLabor: 'Mano de Obra',
    cn_driveTime: 'Tiempo de Manejo',
    cn_hoursByUnit: 'Horas por Unidad',
    cn_fringe: 'Fringe',
    cn_prevailingWage: 'Salario Vigente',
    cn_bond: 'Fianza',
    cn_terms: 'Términos',
    cn_searchUnitsPlaceholder: 'Buscar por nombre, condado, tipo de trabajo…',
    cn_clearSearch: 'Limpiar búsqueda',
    cn_noPayrollYet: 'Aún no hay datos de nómina',
    cn_byEmployee: 'Por empleado',
    cn_regHrs: 'Hrs reg',
    cn_driveHrs: 'Hrs manejo',
    cn_grossLabel: 'Bruto',
    cn_projectDuration: 'Duración del Proyecto',
    cn_projectEnded: 'Proyecto terminado',
    cn_noDates: 'No hay fechas para este proyecto',
    cn_keyDates: 'Fechas Clave',
    cn_projectStart: 'Inicio del Proyecto',
    cn_projectEnd: 'Fin del Proyecto',
    cn_unitsLabel: 'Unidades',
    cn_unitStatus: 'Estado de Unidad',
    // Admin pages
    ap_settings: 'Configuración',
    ap_vehicles: 'Vehículos',
    ap_equipment: 'Herramientas',
    ap_safetyCerts: 'Seguridad y Certs',
    ap_expenses: 'Gastos',
    ap_analytics: 'Analítica',
    ap_competitor: 'Datos Competidores',
    ap_loadingGeneric: 'Cargando...',
    ap_noDataYet: 'Aún no hay datos',
    ap_addRecord: 'Agregar',
    ap_searchPlaceholder: 'Buscar...',
    ap_save: 'Guardar',
    ap_cancel: 'Cancelar',
    ap_delete: 'Eliminar',
    ap_edit: 'Editar',
    ap_view: 'Ver',
    ap_active: 'Activo',
    ap_inactive: 'Inactivo',
    ap_total: 'Total',
    ap_company: 'Empresa',
    ap_status: 'Estado',
    ap_actions: 'Acciones',
    ap_categoryLabel: 'Categoría',
    ap_amountLabel: 'Monto',
    ap_dateLabel: 'Fecha',
    ap_yes: 'Sí',
    ap_no: 'No',
  },
}
