/**
 * Test: each unit-ingest parser produces the expected canonical rows
 * from its known-good fixture file.
 *
 * Run nightly. Catches regressions like "we changed pdfjs's text item
 * shape" or "the xlsx parser silently lost the Property → notes
 * mapping". Pure file IO + parser invocation — no DB, no Drive, no
 * webhook. Safe to run as often as we want.
 *
 * Fixtures live at lib/tests/fixtures/unit-ingest/. Generated by
 * scripts/generate-test-fixtures.mjs and committed to git.
 */
import fs from "node:fs";
import path from "node:path";
import type { TestContext, TestModule } from "./_types";
import { parseManulifeAwardedUnits } from "../ingest/parsers/manulife-awarded-units.mjs";
import { parseManulifeDataSheetPdf } from "../ingest/parsers/manulife-data-sheet-pdf.mjs";
import { parseWeyerhaeuserPlantationExam } from "../ingest/parsers/weyerhaeuser-plantation-exam.mjs";
import { parseDnrReforContract } from "../ingest/parsers/dnr-refor-contract.mjs";
import { parseUsaceTaskOrder } from "../ingest/parsers/usace-task-order.mjs";
import { parseHoodRiverVegetationControl } from "../ingest/parsers/hood-river-vegetation-control.mjs";

const FIXTURE_DIR = path.resolve(process.cwd(), "lib/tests/fixtures/unit-ingest");

const mod: TestModule = {
  name: "unit-ingest-parser-health",
  description: "Each ingest parser handles its known-good fixture (xlsx + PDF + WY filename pattern)",
  severity: "warning",

  async run(ctx: TestContext) {
    const failures: string[] = [];

    // ── Manulife xlsx ─────────────────────────────────────────────
    try {
      const xlsxPath = path.join(FIXTURE_DIR, "manulife-test-fake-Awarded-Units.xlsx");
      const buf = fs.readFileSync(xlsxPath);
      const result = parseManulifeAwardedUnits(buf);

      ctx.step("manulife-xlsx.fixture_present", true, { path: xlsxPath });
      ctx.step("manulife-xlsx.row_count_5", result.parsed.length === 5, { got: result.parsed.length });
      if (result.parsed.length !== 5) failures.push(`manulife-xlsx: expected 5 rows, got ${result.parsed.length}`);

      const first = result.parsed[0]?.canonicalRow ?? {};
      const nameOk = first.name === "TEST UNIT 1 — DELETE ME";
      ctx.step("manulife-xlsx.first_row_name", nameOk, { got: first.name });
      if (!nameOk) failures.push(`manulife-xlsx: first row name wrong (${first.name})`);

      const acresOk = first.amount === 12.34 && first.amount_type === "acre";
      ctx.step("manulife-xlsx.first_row_acres", acresOk, { amount: first.amount, type: first.amount_type });
      if (!acresOk) failures.push(`manulife-xlsx: first row acres wrong`);

      const noUnmapped = (result.parsed as Array<{ unmappedFields: Record<string, unknown> }>)
        .every((p) => Object.keys(p.unmappedFields).length === 0);
      ctx.step("manulife-xlsx.zero_unmapped", noUnmapped);
      if (!noUnmapped) failures.push(`manulife-xlsx: parser left unmapped fields (schema may have drifted)`);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      ctx.step("manulife-xlsx.parse", false, { error: msg });
      failures.push(`manulife-xlsx: ${msg}`);
    }

    // ── Manulife data-sheet PDF ───────────────────────────────────
    try {
      const pdfPath = path.join(FIXTURE_DIR, "manulife-test-fake-Data-sheet.pdf");
      const buf = fs.readFileSync(pdfPath);
      const result = await parseManulifeDataSheetPdf(buf);

      ctx.step("manulife-pdf.fixture_present", true);
      ctx.step("manulife-pdf.row_count_5", result.parsed.length === 5, { got: result.parsed.length });
      if (result.parsed.length !== 5) failures.push(`manulife-pdf: expected 5 rows, got ${result.parsed.length}`);

      const first = (result.parsed[0]?.canonicalRow ?? {}) as Record<string, unknown>;
      const nameOk = first.name === "TEST UNIT 1 — DELETE ME";
      const stateOk = first.state === "Testland";
      ctx.step("manulife-pdf.first_row_extracted", nameOk && stateOk, {
        name: first.name, state: first.state,
      });
      if (!nameOk) failures.push(`manulife-pdf: first row name wrong`);
      if (!stateOk) failures.push(`manulife-pdf: state extraction broke (heuristic regression)`);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      ctx.step("manulife-pdf.parse", false, { error: msg });
      failures.push(`manulife-pdf: ${msg}`);
    }

    // ── Weyerhaeuser PlantationExam (filename-based) ──────────────
    try {
      const wyPath = path.join(FIXTURE_DIR, "PlantationExam_UnitNoPlots_TESTID0001.pdf");
      const buf = fs.readFileSync(wyPath);
      // Parser is now async — OCR path attempts Vision API first then
      // falls back to filename-only when OCR isn't available or fails.
      const result = await parseWeyerhaeuserPlantationExam(buf, {
        filename: "PlantationExam_UnitNoPlots_TESTID0001.pdf",
      });

      ctx.step("wy-pdf.fixture_present", true);
      ctx.step("wy-pdf.row_count_1", result.parsed.length === 1, { got: result.parsed.length });
      if (result.parsed.length !== 1) failures.push(`wy-pdf: expected 1 row, got ${result.parsed.length}`);

      const first = result.parsed[0]?.canonicalRow ?? {};
      const standKeyOk = first.stand_key === "TESTID0001";
      ctx.step("wy-pdf.stand_key_from_filename", standKeyOk, { got: first.stand_key });
      if (!standKeyOk) failures.push(`wy-pdf: stand_key extraction from filename broke`);

      const realFilenameResult = await parseWeyerhaeuserPlantationExam(buf, {
        filename: "PlantationExam_UnitNoPlots_1995281517.pdf",
      });
      const realStandKey = realFilenameResult.parsed[0]?.canonicalRow?.stand_key;
      const realOk = realStandKey === "1995281517";
      ctx.step("wy-pdf.real_filename_pattern_works", realOk, { got: realStandKey });
      if (!realOk) failures.push(`wy-pdf: real WY filename pattern stopped working`);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      ctx.step("wy-pdf.parse", false, { error: msg });
      failures.push(`wy-pdf: ${msg}`);
    }

    // ── DNR refor contract (synthetic) ────────────────────────────
    try {
      const dnrPath = path.join(FIXTURE_DIR, "Contract_99001 Refor TEST ALPHA.pdf");
      const buf = fs.readFileSync(dnrPath);
      const result = await parseDnrReforContract(buf);
      ctx.step("dnr.fixture_present", true);
      ctx.step("dnr.row_count_2", result.parsed.length === 2, { got: result.parsed.length });
      if (result.parsed.length !== 2) failures.push(`dnr: expected 2 rows, got ${result.parsed.length}`);
      const first = result.parsed[0]?.canonicalRow as Record<string, unknown> | undefined;
      const nameOk = typeof first?.name === "string" && (first.name as string).includes("TEST-DNR");
      ctx.step("dnr.first_row_test_name", nameOk, { got: first?.name });
      if (!nameOk) failures.push(`dnr: first-row name should include TEST-DNR (got ${first?.name})`);
      const stateOk = first?.state === "WA" && first?.county === "Testville";
      ctx.step("dnr.legal_location", stateOk, { state: first?.state, county: first?.county });
      if (!stateOk) failures.push(`dnr: Legal Location extraction broke`);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      ctx.step("dnr.parse", false, { error: msg });
      failures.push(`dnr: ${msg}`);
    }

    // ── USACE task order (synthetic) ──────────────────────────────
    try {
      const usacePath = path.join(FIXTURE_DIR, "Task Order W912DW99001 TEST ALPHA.pdf");
      const buf = fs.readFileSync(usacePath);
      const result = await parseUsaceTaskOrder(buf);
      ctx.step("usace.fixture_present", true);
      ctx.step("usace.row_count_2", result.parsed.length === 2, { got: result.parsed.length });
      if (result.parsed.length !== 2) failures.push(`usace: expected 2 rows, got ${result.parsed.length}`);
      const first = result.parsed[0]?.canonicalRow as Record<string, unknown> | undefined;
      const clinOk = typeof first?.name === "string" && (first.name as string).startsWith("CLIN ");
      ctx.step("usace.clin_name", clinOk, { got: first?.name });
      if (!clinOk) failures.push(`usace: name should start with 'CLIN ' (got ${first?.name})`);
      const stateOk = first?.state === "WA";
      ctx.step("usace.state_pnw_filter", stateOk, { state: first?.state });
      if (!stateOk) failures.push(`usace: PNW state filter broke (got ${first?.state})`);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      ctx.step("usace.parse", false, { error: msg });
      failures.push(`usace: ${msg}`);
    }

    // ── Hood River master agreement (synthetic) ──────────────────
    try {
      const hrPath = path.join(FIXTURE_DIR, "Ground Vegetation Control Bid TEST ALPHA.pdf");
      const buf = fs.readFileSync(hrPath);
      const result = await parseHoodRiverVegetationControl(buf);
      ctx.step("hr.fixture_present", true);
      // Master agreement always queues exactly one placeholder
      ctx.step("hr.row_count_1", result.parsed.length === 1, { got: result.parsed.length });
      if (result.parsed.length !== 1) failures.push(`hr: expected 1 placeholder row, got ${result.parsed.length}`);
      const first = result.parsed[0];
      const sowWarning = (first?.warnings ?? []).some((w: string) =>
        /needs_sow_attachment/.test(w),
      );
      ctx.step("hr.sow_warning", sowWarning);
      if (!sowWarning) failures.push(`hr: missing needs_sow_attachment warning`);
      const row = first?.canonicalRow as Record<string, unknown> | undefined;
      const stateOk = row?.state === "OR";
      ctx.step("hr.state_oregon", stateOk, { state: row?.state });
      if (!stateOk) failures.push(`hr: state should be OR (got ${row?.state})`);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      ctx.step("hr.parse", false, { error: msg });
      failures.push(`hr: ${msg}`);
    }

    if (failures.length === 0) return { ok: true, steps: [], cleanup_ok: true };
    return {
      ok: false,
      error: `${failures.length} parser check(s) failed: ${failures.join("; ")}`,
      steps: [],
      cleanup_ok: true,
    };
  },
};

export default mod;
